export const FETCH_WEATHER_FORECAST = 'FETCH_WEATHER_FORECAST';
export const FETCH_WEATHER_ATTEMPT = 'FETCH_WEATHER_ATTEMPT';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';